version: '3'
services:
  db:
    image: mysql:8.0.26
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/root/root.mylogin.cnf:/root/.mylogin.cnf
      - ./mysql/sql:/tmp/sql
    env_file:
      - ./mysql/.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db
